apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 21000
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb-system
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: port 
      protocol: TCP
      port: 21000
      targetPort: 21000
